#pragma once

#define MASTER_RIGHT
#define NO_MUSIC_MODE
#define NO_ACTION_ONESHOT
#define LAYER_STATE_8BIT // レイヤー0から7まで
#define PAW3204_SCLK_PIN D0
#define PAW3204_SDIO_PIN D1

#define COMBO_COUNT 10
#define COMBO_TERM 12

#define TAPPING_TERM 185
#define TAPPING_TERM_PER_KEY

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 4
#define AUTO_MOUSE_TIME 1200
#define AUTO_MOUSE_THRESHOLD 5

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
